package y25

import common.puzzle.Input
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class Day7Test {
    private val sample = Input("""
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
    """.trimIndent())

    private val day = Day7(sample)

    @Test
    fun solveLevel1() {
        assertEquals(21, day.solveLevel1())
    }

    @Test
    fun solveLevel2() {
         assertEquals(40L, day.solveLevel2())
    }
}
