package y24

import common.puzzle.Input
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

internal class Day8Test {
    private val sample = Input("""
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """.trimIndent())

    private val day = Day8(sample)

    @Test
    fun solveLevel1() {
        assertEquals(14, day.solveLevel1())
    }

    @Test
    fun solveLevel2() {
         assertEquals(34, day.solveLevel2())
    }
}
